import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
const read=x=>readFileSync(new URL('../'+x,import.meta.url),'utf8').replace(/^import .*\n/gm,'').replace(/^export /gm,'');
function harness(){const nodes={'#app':{innerHTML:''},'#overlay-root':{innerHTML:''},'#toast-root':{innerHTML:''}};const ctx=vm.createContext({document:{querySelector:x=>nodes[x]||null,querySelectorAll:()=>[],activeElement:null,addEventListener(){},body:{style:{}}},location:{hash:''},history:{pushState(){}},window:{addEventListener(){}},requestAnimationFrame(){},console,setTimeout,clearTimeout});vm.runInContext(read('catalog-images.js')+read('art.js')+read('icons.js')+read('app.js').replace(/initialize\(\);\s*$/,'')+'\nglobalThis.ui={state,render,renderDialog,voiceStage,productArt};',ctx);ctx.ui.state.bootstrap={customers:[],catalog:[],policy:{version:'test-policy'},capabilities:{voice:{status:'unconfigured'}}};return{...ctx.ui,nodes};}
const replay={id:'offline-test',kind:'historical-replay',source:{items:[{product:{name:'Test historical shirt'},size:'M',orderStatus:'Refund Completed'}]},candidates:[{ref:'public-test',name:'Test candidate',url:'https://example.test/item',material:null,fit:null,gsm:null,priceInr:null,availability:null,solvesComplaint:null,materialSafety:null}],messages:[{role:'user',text:'Actual current fixture feedback',source:'assemblyai',itemId:'provider-test'}],tools:[],pendingAction:{proposalId:'p1',productRef:'public-test'},currentMerchantEligibility:null};
test('prepared receipt is never live and source selector requires explicit capability',()=>{const h=harness();h.render();assert.doesNotMatch(h.nodes['#app'].innerHTML,/Historical replay<|Live provider session/);h.state.replaySnapshot={id:'receipt',sourceItem:{name:'Test source'}};h.render();assert.match(h.nodes['#app'].innerHTML,/Prepared replay · not live/);assert.doesNotMatch(h.nodes['#app'].innerHTML,/data-action="refund"/);});
test('replay unknowns and current transcript render without fixture customer/history',()=>{const h=harness();h.state.session=structuredClone(replay);h.render();const html=h.nodes['#app'].innerHTML;assert.match(html,/Actual current fixture feedback/);assert.match(html,/GSM unknown/);assert.match(html,/Material unknown/);assert.match(html,/Complaint resolution and material safety unverified/);assert.doesNotMatch(html,/Request refund|Review exchange|Demo inventory|Orders<\/span>|Customer histories, inventory, and transactions are simulated/);});
test('replay confirmation only records app-owned choice',()=>{const h=harness();h.state.session=structuredClone(replay);h.state.dialog={type:'confirm'};h.renderDialog();const html=h.nodes['#overlay-root'].innerHTML;assert.match(html,/Confirm replay choice/);assert.match(html,/App-owned replay_selection/);assert.doesNotMatch(html,/condition-confirmed|Confirm exchange|Confirm refund/);});
test('replay outcome never claims merchant transaction',()=>{const h=harness();h.state.session={...structuredClone(replay),pendingAction:null,resolution:{kind:'replay_selection',selectedProductRef:'public-test',merchantActionExecuted:false}};h.render();assert.match(h.nodes['#app'].innerHTML,/No merchant action executed/);assert.doesNotMatch(h.nodes['#app'].innerHTML,/refund recorded|exchange recorded/i);});
test('audio labels follow actual voice state and mute flag',()=>{const h=harness();h.state.voiceStatus='speaking';assert.match(h.voiceStage(),/Agent speaking/);assert.doesNotMatch(h.voiceStage(),/>Listening</);h.state.voiceStatus='listening';assert.match(h.voiceStage(),/>Listening</);h.state.voiceMuted=true;assert.match(h.voiceStage(),/Microphone muted/);h.state.voiceStatus='connecting';assert.doesNotMatch(h.voiceStage(),/>Listening</);});
test('withdrawn recommendation closes stale dialog even while busy',()=>{const h=harness();h.state.session={candidates:[],recommendationAllowed:false};h.state.busy=true;h.state.dialog={type:'compare',data:{id:'old'}};h.nodes['#overlay-root'].innerHTML='old dialog';h.renderDialog();assert.equal(h.state.dialog,null);assert.equal(h.nodes['#overlay-root'].innerHTML,'');});
test('catalog imagery uses exact source URLs and rejects unsafe image sources',()=>{const h=harness();assert.match(h.productArt({name:'Midnight',catalogSource:{url:'https://www.thesouledstore.com/product/armour-tshirt-midnight-men-oversized-tshirt'}}),/midnight.png/);assert.doesNotMatch(h.productArt({name:'Unmatched',imageUrl:'javascript:alert(1)'}),/<img|<svg/);assert.match(h.productArt({name:'Unmatched'}),/photograph unavailable/);});
