import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import test from 'node:test';
const read=x=>readFileSync(new URL('../'+x,import.meta.url),'utf8').replace(/^import .*\n/gm,'').replace(/^export /gm,'');
function harness(){const nodes={'#app':{innerHTML:''},'#overlay-root':{innerHTML:''},'#toast-root':{innerHTML:''}};const ctx=vm.createContext({document:{querySelector:x=>nodes[x]||null,querySelectorAll:()=>[],activeElement:null,addEventListener(){},body:{style:{}}},location:{hash:''},history:{pushState(){}},window:{addEventListener(){}},requestAnimationFrame(){},console,setTimeout,clearTimeout});vm.runInContext(read('catalog-images.js')+read('art.js')+read('icons.js')+read('app.js').replace(/initialize\(\);\s*$/,'')+'\nglobalThis.ui={state,render,renderDialog,voiceStage,productArt,photoWipe,compactMeasurements,displayReason,customerComparisonQuote,shouldShowWelcome,welcomeView};',ctx);ctx.ui.state.bootstrap={customers:[],catalog:[],policy:{version:'test-policy'},capabilities:{voice:{status:'unconfigured'}}};return{...ctx.ui,nodes};}
const replay={id:'offline-test',kind:'historical-replay',source:{items:[{product:{name:'Test historical shirt'},size:'M',orderStatus:'Refund Completed'}]},candidates:[{ref:'public-test',name:'Test candidate',url:'https://example.test/item',material:null,fit:null,gsm:null,priceInr:null,availability:null,solvesComplaint:null,materialSafety:null}],messages:[{role:'user',text:'Actual current fixture feedback',source:'assemblyai',itemId:'provider-test'}],tools:[],pendingAction:{proposalId:'p1',productRef:'public-test'},currentMerchantEligibility:null};
test('prepared receipt is never live and source selector requires explicit capability',()=>{const h=harness();h.render();assert.doesNotMatch(h.nodes['#app'].innerHTML,/Historical replay<|Live provider session/);h.state.replaySnapshot={id:'receipt',sourceItem:{name:'Test source'}};h.render();assert.match(h.nodes['#app'].innerHTML,/Prepared replay · not live/);assert.doesNotMatch(h.nodes['#app'].innerHTML,/data-action="refund"/);});
test('replay unknowns and current transcript render without fixture customer/history',()=>{const h=harness();h.state.session=structuredClone(replay);h.render();const html=h.nodes['#app'].innerHTML;assert.match(html,/Actual current fixture feedback/);assert.match(html,/GSM unknown/);assert.match(html,/Material unknown/);assert.match(html,/Complaint resolution and material safety unverified/);assert.doesNotMatch(html,/Request refund|Review exchange|Demo inventory|Orders<\/span>|Customer histories, inventory, and transactions are simulated/);});
test('replay confirmation only records app-owned choice',()=>{const h=harness();h.state.session=structuredClone(replay);h.state.dialog={type:'confirm'};h.renderDialog();const html=h.nodes['#overlay-root'].innerHTML;assert.match(html,/Confirm replay choice/);assert.match(html,/App-owned replay_selection/);assert.doesNotMatch(html,/condition-confirmed|Confirm exchange|Confirm refund/);});
test('replay outcome never claims merchant transaction',()=>{const h=harness();h.state.session={...structuredClone(replay),pendingAction:null,resolution:{kind:'replay_selection',selectedProductRef:'public-test',merchantActionExecuted:false}};h.render();assert.match(h.nodes['#app'].innerHTML,/No merchant action executed/);assert.doesNotMatch(h.nodes['#app'].innerHTML,/refund recorded|exchange recorded/i);});
test('audio labels follow actual voice state and mute flag',()=>{const h=harness();h.state.voiceStatus='speaking';assert.match(h.voiceStage(),/Agent speaking/);assert.doesNotMatch(h.voiceStage(),/>Listening</);h.state.voiceStatus='listening';assert.match(h.voiceStage(),/>Listening</);h.state.voiceMuted=true;assert.match(h.voiceStage(),/Microphone muted/);h.state.voiceStatus='connecting';assert.doesNotMatch(h.voiceStage(),/>Listening</);});
test('withdrawn recommendation closes stale dialog even while busy',()=>{const h=harness();h.state.session={candidates:[],recommendationAllowed:false};h.state.busy=true;h.state.dialog={type:'compare',data:{id:'old'}};h.nodes['#overlay-root'].innerHTML='old dialog';h.renderDialog();assert.equal(h.state.dialog,null);assert.equal(h.nodes['#overlay-root'].innerHTML,'');});
test('catalog imagery uses exact source URLs and rejects unsafe image sources',()=>{const h=harness();assert.match(h.productArt({name:'Midnight',catalogSource:{url:'https://www.thesouledstore.com/product/armour-tshirt-midnight-men-oversized-tshirt'}}),/midnight.png/);assert.doesNotMatch(h.productArt({name:'Unmatched',imageUrl:'javascript:alert(1)'}),/<img|<svg/);assert.match(h.productArt({name:'Unmatched'}),/photograph unavailable/);});

test('wipe uses verified photos, native keyboard control and explicit geometry boundary',()=>{const h=harness();const a={name:'Source',catalogSource:{url:'https://www.thesouledstore.com/product/armour-tshirt-midnight-men-oversized-tshirt'}},b={name:'Candidate',catalogSource:{url:'https://www.thesouledstore.com/product/dc-darkseid-men-oversized-tshirt'}};h.state.dialog={type:'compare'};const html=h.photoWipe(a,b);assert.match(html,/type="range"/);assert.match(html,/Returned photo/);assert.match(html,/Alternative photo/);assert.match(html,/unaligned scale and pose/);assert.match(html,/does not compare garment geometry or simulate fit/);assert.match(html,/midnight.png/);assert.match(html,/darkseid.png/);assert.doesNotMatch(h.photoWipe(a,{name:'Unknown'}),/type="range"/);});
test('measurement deltas preserve unknowns and quote actual session words',()=>{const h=harness();const html=h.compactMeasurements({gsm:250,garmentMeasurements:{M:{chestIn:46}}},'M',{gsm:220,garmentMeasurements:{L:{chestIn:48}}},'L');assert.match(html,/\+2 in/);assert.match(html,/-30 GSM/);assert.match(html,/Unknown/);assert.match(html,/difference unknown/);h.state.session={messages:[{role:'user',text:'I like the fit, but the fabric feels heavy.'}]};assert.match(h.customerComparisonQuote(),/I like the fit, but the fabric feels heavy/);assert.equal(h.displayReason('6 in stock in L'),'6 simulated units in stock in L');});
test('changed-mind snapshot clears stale proposal without cancel, including during busy update',()=>{const h=harness();h.state.busy=true;h.state.session={pendingAction:null};h.state.dialog={type:'confirm'};h.nodes['#overlay-root'].innerHTML='stale';h.renderDialog();assert.equal(h.state.dialog,null);assert.equal(h.nodes['#overlay-root'].innerHTML,'');});

for(const [name,labels,secondary] of [
 ['two grounded change constraints',['fit_too_small','material_too_heavy'],['material.too_heavy']],
 ['three grounded change constraints',['fit_too_small','material_too_heavy','appearance_mismatch'],['material.too_heavy','appearance.mismatch']],
])test(name+' appear in actual main and modal render while explicit keeps remain',()=>{const h=harness();const original={id:'source',name:'Returned',sizes:['M'],colors:['listed product variant'],stock:{M:6}},product={id:'candidate',name:'Alternative',sizes:['M'],colors:['listed product variant'],stock:{M:6}};const candidate={product,recommendedSize:'M',why:[]};h.state.bootstrap.catalog=[original,product];h.state.session={id:'test',sourceProduct:original,item:{productId:'source',size:'M'},candidates:[candidate],recommendationAllowed:true,diagnosis:{primaryReason:'fit.shoulders_tight',secondaryReasons:secondary,labels,likedAttributes:['theme','color']},messages:[{role:'user',text:'Actual current complaint'}]};h.render();h.state.dialog={type:'compare',data:candidate};h.renderDialog();for(const html of [h.nodes['#app'].innerHTML,h.nodes['#overlay-root'].innerHTML]){const summary=html.match(/class="stencil-constraints"[^>]*>([\s\S]*?)<\/div>/)?.[1];assert.ok(summary);assert.match(summary,/<b>KEEP<\/b> Theme . Color/);assert.match(summary,/Fit shoulders tight/);assert.match(summary,/Fit too small/);assert.match(summary,/Material too heavy/);if(labels.length===3)assert.match(summary,/Appearance mismatch/);assert.equal((summary.match(/Material too heavy/g)||[]).length,1);}});

test('first visit introduces the workflow while existing sessions and recording routes bypass entry',()=>{const h=harness();const route={hostname:'127.0.0.1',search:'',hash:''};assert.equal(h.shouldShowWelcome(route),true);assert.equal(h.shouldShowWelcome(route,true),false);assert.equal(h.shouldShowWelcome(route,false,true),false);assert.equal(h.shouldShowWelcome({...route,hash:'#intelligence'}),false);assert.equal(h.shouldShowWelcome({...route,search:'?testAudio=1&receipt=fixture'}),false);assert.equal(h.shouldShowWelcome({...route,hostname:'localhost',search:'?testAudio=1'}),false);assert.equal(h.shouldShowWelcome({...route,hostname:'judge.example',search:'?testAudio=1'}),true);const html=h.welcomeView();assert.match(html,/data-action="enter-demo"/);assert.match(html,/Public text demo/);assert.match(html,/live audio is disabled/);assert.match(html,/No real refund, payment, order, or delivery/);assert.doesNotMatch(html,/<video|watch video|href=.*video/i);});
test('landing illustration stays static-readable and never impersonates live provider results',()=>{const h=harness();const html=h.welcomeView();assert.equal((html.match(/class="sequence-step /g)||[]).length,4);assert.match(html,/Illustrative · not live/);assert.match(html,/Only after customer confirmation/);assert.match(html,/Simulated exchange/);assert.match(html,/Fit and comfort not guaranteed/);assert.match(html,/assets\/catalog\/midnight.png/);assert.match(html,/assets\/catalog\/coast.png/);assert.equal((html.match(/<button/g)||[]).length,1);assert.doesNotMatch(html,/<audio|<video|aria-live|Agent speaking|Listening/);const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.sequence-step\{animation:none;opacity:1;transform:none\}\}/);assert.doesNotMatch(css,/sequence-arrive[^;}]*infinite/);});
