import { REPLAY_SOURCE_PRODUCTS } from '../agent/lib/knowledge/replay-source-products.ts';
import {AsyncLocalStorage} from 'node:async_hooks';
import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {providerHistorySchema} from './private/provider-history.ts';
import {PUBLIC_CATALOG_EVIDENCE} from '../agent/lib/knowledge/public-catalog.ts';
import {MERCHANDISING_COLLECTION} from '../agent/lib/knowledge/merchandising.ts';
import {diagnoseReturn} from '../agent/lib/engine/diagnosis.ts';
import {revokesMaterialExploration} from '../agent/lib/engine/consent.ts';
import {appendRecord,type AppRecord} from '../agent/lib/engine/records.ts';
import {DomainError,discountDecision} from '../agent/lib/demo/service.ts';
const selectionSchema=z.object({recordId:z.string(),kind:z.literal('replay_selection'),sessionId:z.string(),createdAt:z.string(),proposalId:z.string(),selectedProductRef:z.string(),sourceStatus:z.literal('Refund Completed'),simulated:z.literal(true),merchantActionExecuted:z.literal(false)}).strict();
const stateSchema=z.object({kind:z.literal('historical-replay'),id:z.string().uuid(),createdAt:z.string(),source:providerHistorySchema,sourceHash:z.string(),feedback:z.string().nullable(),consent:z.boolean(),presented:z.array(z.string()),pending:z.object({proposalId:z.string(),productRef:z.string()}).strict().nullable(),selection:selectionSchema.nullable(),messages:z.array(z.object({id:z.string(),role:z.enum(['user','assistant']),text:z.string(),at:z.string(),itemId:z.string().optional(),interrupted:z.boolean().optional(),source:z.literal('assemblyai')})),tools:z.array(z.object({id:z.string(),callId:z.string(),name:z.string(),origin:z.literal('model'),at:z.string(),durationMs:z.number(),result:z.unknown()})),toolResults:z.array(z.object({callId:z.string(),result:z.unknown()}))}).strict();
type State=z.infer<typeof stateSchema>;
const memory=new Map<string,State>();const context=new AsyncLocalStorage<Map<string,State>>();const states=()=>context.getStore()??memory;
export function withReplayContext<T>(work:()=>T):T{return context.run(new Map(),work);}
export function replaySessionIds(){return [...states().keys()];}
export function isReplaySession(id:string){return states().has(id);}
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function get(id:string){const s=states().get(id);if(!s)throw new DomainError('session_not_found','Historical replay session unavailable.',404);return s;}
export function hydrateReplaySession(input:unknown){const s=stateSchema.parse(input);if(s.sourceHash!==hash(s.source))throw new Error('Immutable historical projection changed.');states().set(s.id,s);return replaySnapshot(s.id);}
export function serializeReplaySession(id:string){return structuredClone(get(id));}
export function startReplaySession(sourceInput:unknown){const source=providerHistorySchema.parse(sourceInput);if(source.items.length!==1||source.items[0]!.orderStatus!=='Refund Completed')throw new DomainError('invalid_replay_source','Select one already-refunded historical source; no current merchant eligibility.',400);const s:State={kind:'historical-replay',id:randomUUID(),createdAt:new Date().toISOString(),source,sourceHash:hash(source),feedback:null,consent:false,presented:[],pending:null,selection:null,messages:[],tools:[],toolResults:[]};states().set(s.id,s);return replaySnapshot(s.id);}
function allowed(s:State){if(!s.feedback)return false;const d=diagnoseReturn(s.feedback);return !d.refundOnly&&!d.frustrated&&!d.labels.some(l=>l==='quality_defect'||l==='wrong_item')&&(d.recommendationAllowed||(d.labels.includes('sensitive_skin_reaction')&&s.consent));}
function publicProduct(ref:string){const p=PUBLIC_CATALOG_EVIDENCE.products.find(p=>p.id===ref);if(p)return {ref,name:p.name,url:p.productUrl,material:p.material,fit:p.fit,gsm:p.gsm,priceInr:p.priceInr,availability:null,solvesComplaint:null,materialSafety:null,claim:null};const m=MERCHANDISING_COLLECTION.items.find(p=>p.ref===ref);if(m)return {ref,name:m.name,url:m.url,material:m.material,fit:null,gsm:null,priceInr:null,availability:null,solvesComplaint:null,materialSafety:null,claim:MERCHANDISING_COLLECTION.permittedClaim};throw new DomainError('unknown_product','Product lacks exact public evidence.',400);}
export function replaySnapshot(id:string){const s=get(id);return {id:s.id,kind:s.kind,mode:'assemblyai' as const,replay:true,nonTransactional:true,phase:s.selection?'COMPLETED':s.pending?'AWAITING_CONFIRMATION':s.feedback?'REPLAY_FEEDBACK':'REPLAY_LOOKUP',source:s.source,sourceHash:s.sourceHash,currentMerchantEligibility:null,feedback:s.feedback,sensitiveExplorationConsent:s.consent,candidates:allowed(s)?s.presented.map(publicProduct):[],pendingAction:s.pending,resolution:s.selection,items:[{resolution:s.selection?{...s.selection,kind:"outcome" as const,eventKind:"replay_selection"}:null}],messages:s.messages,tools:s.tools,status:'Historical replay; app-owned selection only; no merchant transaction',boundaryNotice:'Historical source remains Refund Completed. Dates and private identity are excluded. Stock and current eligibility are unknown; material comfort is not guaranteed.'};}
export function replayTranscript(id:string,input:{role:'user'|'assistant';text:string;itemId?:string;interrupted?:boolean}){const s=get(id);if(input.itemId&&s.messages.some(m=>m.role===input.role&&m.itemId===input.itemId))return replaySnapshot(id);s.messages.push({id:randomUUID(),...input,at:new Date().toISOString(),source:'assemblyai'});return replaySnapshot(id);}
export function replayProviderConfig(id:string){const s=get(id);return {system_prompt:`You are an AI assistant in a clearly labeled historical feedback replay, no merchant integration. The historical source was already refunded and stays immutable. Diagnose only the customer's CURRENT spoken feedback; never invent a past return cause, kept/liked preference, stock, cohort success, current eligibility or a merchant transaction. Use only the listed replay tools, never fixture customer/order tools. Ask one question at a time, allow interruption and no pressure. Canonical policy allows no discretionary discount; use get_discount_policy and don't escalate solely for discounts. Skin complaints: no safety/medical guarantees, no alternatives without explicit permission, and permission never overrides defects, refund-only or frustration gates. request_replay_selection prepares app-owned interest only; the customer must confirm on screen. Only application evidence may establish that an app-owned replay_selection was recorded. Source product, size and historical status: ${JSON.stringify(s.source.items[0])}`,
 greeting:"This is a historical feedback replay. Your previous refund remains completed. What would you like to tell me about the product now?",
 input:{format:{encoding:'audio/pcm'},language_codes:['en'],transcription_mode:'balanced',turn_detection:{interrupt_response:true,interruption_delay:100}},output:{voice:'alba',format:{encoding:'audio/pcm'}},tools:[
 ['lookup_historical_item','Read only sanitized public product, size and immutable historical status.',{}],['get_discount_policy','Canonical no-discretionary-discount refusal, no unnecessary escalation.',{}],['diagnose_replay_feedback','Diagnose exact current customer transcript; no historical cause inference.',{text:{type:'string'}}],['search_replay_products','Read grounded public alternatives with unknown stock and no promised resolution.',{}],['request_replay_selection','Prepare app-owned interest for explicit on-screen confirmation, never a merchant exchange.',{productRef:{type:'string'}}]
 ].map(([name,description,properties])=>({type:'function',name,description,execution_mode:'interactive',timeout_seconds:15,parameters:{type:'object',properties,additionalProperties:false,...(name==='diagnose_replay_feedback'?{required:['text']}:name==='request_replay_selection'?{required:['productRef']}: {})}}))};}
export function executeReplayTool(id:string,call:{callId:string;name:string;arguments:unknown}){const s=get(id);const previous=s.toolResults.find(p=>p.callId===call.callId);if(previous)return {result:previous.result,snapshot:replaySnapshot(id)};const started=performance.now();let result:unknown;
 switch(call.name){
 case 'lookup_historical_item':z.object({}).strict().parse(call.arguments);result={...s.source, currentMerchantEligibility:null};break;
 case 'get_discount_policy':z.object({}).strict().parse(call.arguments);result=discountDecision();break;
 case 'diagnose_replay_feedback':{const {text}=z.object({text:z.string().min(1).max(4000)}).strict().parse(call.arguments);const latest=[...s.messages].reverse().find(m=>m.role==='user');if(!latest||latest.text!==text)throw new DomainError('ungrounded_feedback','Use exact current customer transcript.',409);if(s.selection)throw new DomainError('already_resolved','Replay interest already recorded.',409);s.feedback=s.feedback? s.feedback+'\n'+text:text;const d=diagnoseReturn(s.feedback);if(d.refundOnly||d.frustrated||revokesMaterialExploration(text))s.consent=false;else if(d.labels.includes('sensitive_skin_reaction')&&/\b(show|explore|want).{0,30}(alternatives|different material)\b/i.test(text))s.consent=true;s.pending=null;s.presented=[];result={labels:d.labels,refundOnly:d.refundOnly,frustrated:d.frustrated,recommendationAllowed:allowed(s),materialSafety:null,pastReturnCause:null};break;}
 case 'search_replay_products':z.object({}).strict().parse(call.arguments);const sourceProduct=[...PUBLIC_CATALOG_EVIDENCE.products,...REPLAY_SOURCE_PRODUCTS].find(p=>new URL(p.productUrl).pathname===new URL(s.source.items[0]!.product?.url??'https://unknown.invalid').pathname);const wantsDifferent=/different material/i.test(s.feedback??'');s.presented=!allowed(s)?[]:wantsDifferent?sourceProduct?.material?PUBLIC_CATALOG_EVIDENCE.products.filter(p=>p.id!==sourceProduct.id&&p.material&&p.material!==sourceProduct.material).slice(0,2).map(p=>p.id):[]:MERCHANDISING_COLLECTION.items.slice(0,2).map(p=>p.ref);result={products:s.presented.map(publicProduct),cohortDataAvailable:false,ranking:null,stockKnown:false,solvesComplaint:null,materialSafety:null};break;
 case 'request_replay_selection':{const {productRef}=z.object({productRef:z.string()}).strict().parse(call.arguments);if(!allowed(s)||!s.presented.includes(productRef))throw new DomainError('unverified_candidate','Choose a presented, permitted grounded alternative.',409);s.pending={proposalId:randomUUID(),productRef};result={requiresHumanConfirmation:true,product:publicProduct(productRef),merchantActionExecuted:false,kind:'replay_selection'};break;}
 default:throw new DomainError('unknown_tool','Fixture/customer/order/merchant tools are unavailable in historical replay.',400);
 }
 s.toolResults.push({callId:call.callId,result});s.tools.push({id:randomUUID(),callId:call.callId,name:call.name,origin:'model',at:new Date().toISOString(),durationMs:performance.now()-started,result});return {result,snapshot:replaySnapshot(id)};
}
export function confirmReplaySelection(id:string,input:{proposalId:string;confirmed:true}){const s=get(id);if(s.selection){if(input.proposalId!==s.selection.proposalId)throw new DomainError('stale_proposal','Replay selection differs from this proposal.',409);return replaySnapshot(id);}if(input.confirmed!==true||!s.pending||s.pending.proposalId!==input.proposalId||!allowed(s)||!s.presented.includes(s.pending.productRef))throw new DomainError('stale_proposal','Current explicit on-screen confirmation is required.',409);const record=appendRecord('outcome',{eventKind:'replay_selection',proposalId:s.pending.proposalId,selectedProductRef:s.pending.productRef,sourceStatus:'Refund Completed',simulated:true,merchantActionExecuted:false},s.id);const {eventKind,...recordView}=record;s.selection=selectionSchema.parse({...recordView,kind:"replay_selection"});s.pending=null;return replaySnapshot(id);}
export function cancelReplaySelection(id:string){get(id).pending=null;return replaySnapshot(id);}

export function replayOutcomeForProvider(record:AppRecord|z.infer<typeof selectionSchema>){if(record.kind!=='replay_selection'&&!(record.kind==='outcome'&&record.eventKind==='replay_selection'))throw new Error('Not a replay outcome.');return {kind:'replay_selection',recorded:true,product:publicProduct(String(record.selectedProductRef)),sourceStatus:'Refund Completed',merchantActionExecuted:false};}
