import type { Product } from "./types.ts";

/**
 * Synthetic demo catalog in the shape of The Souled Store's range.
 * Every attribute the agent can quote lives here — never in the prompt.
 * Stock is per size (colors pooled); a few deliberate zeros keep
 * inventory checks honest in the demo.
 */
export const CATALOG: Product[] = [
  // ---- Oversized t-shirts -------------------------------------------------
  {
    id: "TSS-OBT-001",
    name: "Ink Black Oversized Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 8, M: 12, L: 10, XL: 6, XXL: 3 },
    colors: ["ink black", "charcoal"],
    material: "100% cotton",
    gsm: 240,
    priceInr: 999,
    theme: "solid",
    returnable: true,
    tags: ["heavyweight", "drop-shoulder", "streetwear", "dark"],
  },
  {
    id: "TSS-OBT-002",
    name: "Midnight Orbit Oversized Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 5, M: 9, L: 7, XL: 0 },
    colors: ["midnight navy", "black"],
    material: "100% cotton",
    gsm: 220,
    priceInr: 1099,
    theme: "space print",
    returnable: true,
    tags: ["graphic", "drop-shoulder", "dark", "mid-weight"],
  },
  {
    id: "TSS-OBT-003",
    name: "Cloud Dye Oversized Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: { XS: 4, S: 7, M: 6, L: 5, XL: 2 },
    colors: ["cloud blue", "lilac"],
    material: "100% cotton",
    gsm: 200,
    priceInr: 1149,
    theme: "tie-dye",
    returnable: true,
    tags: ["pastel", "lightweight", "drop-shoulder"],
  },
  {
    id: "TSS-OBT-004",
    name: "Retro Arcade Oversized Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 6, M: 10, L: 8, XL: 4, XXL: 0 },
    colors: ["off white", "mustard"],
    material: "cotton-poly blend",
    gsm: 210,
    priceInr: 1199,
    theme: "retro gaming",
    returnable: true,
    tags: ["graphic", "mid-weight"],
  },
  {
    id: "TSS-OBT-005",
    name: "Aero Knit Oversized Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 9, M: 11, L: 9, XL: 5 },
    colors: ["sage", "stone"],
    material: "cotton-modal blend",
    gsm: 180,
    priceInr: 1249,
    theme: "solid",
    returnable: true,
    tags: ["lightweight", "breathable", "soft-handfeel"],
  },

  // ---- Regular / slim t-shirts ---------------------------------------------
  {
    id: "TSS-RGT-001",
    name: "Essential Crew Tee",
    category: "tshirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 14, M: 18, L: 15, XL: 9, XXL: 4 },
    colors: ["charcoal", "navy", "white", "olive"],
    material: "100% cotton",
    gsm: 240,
    priceInr: 699,
    theme: "solid",
    returnable: true,
    tags: ["basics", "heavyweight"],
  },
  {
    id: "TSS-RGT-002",
    name: "Feather Crew Tee",
    category: "tshirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 10, M: 13, L: 11, XL: 6 },
    colors: ["white", "sky", "mint"],
    material: "cotton-modal blend",
    gsm: 160,
    priceInr: 749,
    theme: "solid",
    returnable: true,
    tags: ["lightweight", "breathable", "summer"],
  },
  {
    id: "TSS-RGT-003",
    name: "Slim Fit Stretch Tee",
    category: "tshirt",
    fit: "slim",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 8, M: 12, L: 10, XL: 5 },
    colors: ["black", "maroon"],
    material: "cotton-elastane blend",
    gsm: 200,
    priceInr: 799,
    theme: "solid",
    returnable: true,
    tags: ["stretch", "fitted"],
  },
  {
    id: "TSS-RGT-004",
    name: "Wander Graphic Tee",
    category: "tshirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 7, M: 9, L: 8, XL: 3, XXL: 0 },
    colors: ["rust", "teal"],
    material: "100% cotton",
    gsm: 180,
    priceInr: 899,
    theme: "travel print",
    returnable: true,
    tags: ["graphic", "lightweight"],
  },
  {
    id: "TSS-RGT-005",
    name: "Studio Relaxed Tee",
    category: "tshirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 6, M: 10, L: 8, XL: 4 },
    colors: ["ecru", "washed black"],
    material: "100% cotton",
    gsm: 210,
    priceInr: 849,
    theme: "solid",
    returnable: true,
    tags: ["mid-weight", "garment-wash"],
  },
  {
    id: "TSS-RGT-006",
    name: "Breeze Relaxed Tee",
    category: "tshirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 11, M: 14, L: 12, XL: 7, XXL: 2 },
    colors: ["white", "peach", "seafoam"],
    material: "cotton-linen blend",
    gsm: 150,
    priceInr: 949,
    theme: "solid",
    returnable: true,
    tags: ["lightweight", "breathable", "summer"],
  },
  {
    id: "TSS-RGT-007",
    name: "Mecha Panel Tee",
    category: "tshirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 5, M: 8, L: 6, XL: 0 },
    colors: ["steel grey", "black"],
    material: "cotton-poly blend",
    gsm: 190,
    priceInr: 999,
    theme: "anime robot",
    returnable: true,
    tags: ["graphic", "mid-weight", "dark"],
  },

  // ---- Polos ---------------------------------------------------------------
  {
    id: "TSS-POL-001",
    name: "Court Slim Polo",
    category: "polo",
    fit: "slim",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 6, M: 9, L: 7, XL: 3 },
    colors: ["navy", "forest"],
    material: "cotton pique",
    gsm: 220,
    priceInr: 1099,
    theme: "solid",
    returnable: true,
    tags: ["smart-casual", "fitted"],
  },
  {
    id: "TSS-POL-002",
    name: "Weekend Regular Polo",
    category: "polo",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 8, M: 10, L: 8, XL: 5, XXL: 2 },
    colors: ["white", "sky", "coral"],
    material: "cotton pique",
    gsm: 210,
    priceInr: 999,
    theme: "solid",
    returnable: true,
    tags: ["smart-casual"],
  },
  {
    id: "TSS-POL-003",
    name: "Knit Relaxed Polo",
    category: "polo",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 4, M: 7, L: 6, XL: 2 },
    colors: ["sand", "brown"],
    material: "cotton knit",
    gsm: 240,
    priceInr: 1299,
    theme: "solid",
    returnable: true,
    tags: ["premium", "soft-handfeel"],
  },

  // ---- Shirts --------------------------------------------------------------
  {
    id: "TSS-SHT-001",
    name: "Oxford Regular Shirt",
    category: "shirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 7, M: 9, L: 8, XL: 4, XXL: 1 },
    colors: ["light blue", "white"],
    material: "cotton oxford",
    priceInr: 1499,
    theme: "solid",
    returnable: true,
    tags: ["smart-casual", "workwear"],
  },
  {
    id: "TSS-SHT-002",
    name: "Linen Relaxed Shirt",
    category: "shirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 5, M: 8, L: 7, XL: 3 },
    colors: ["sage", "ecru", "terracotta"],
    material: "cotton-linen blend",
    priceInr: 1599,
    theme: "solid",
    returnable: true,
    tags: ["breathable", "summer", "resort"],
  },
  {
    id: "TSS-SHT-003",
    name: "Flannel Check Shirt",
    category: "shirt",
    fit: "regular",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 6, M: 8, L: 6, XL: 2 },
    colors: ["red check", "green check"],
    material: "brushed cotton flannel",
    priceInr: 1699,
    theme: "checks",
    returnable: true,
    tags: ["winter", "warm"],
  },
  {
    id: "TSS-SHT-004",
    name: "Vacay Print Shirt",
    category: "shirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 9, M: 11, L: 8, XL: 4 },
    colors: ["tropical print", "mono print"],
    material: "viscose rayon",
    priceInr: 1399,
    theme: "tropical print",
    returnable: true,
    tags: ["lightweight", "resort", "drapey"],
  },

  // ---- Hoodies & sweatshirts -----------------------------------------------
  {
    id: "TSS-HOD-001",
    name: "Core Fleece Hoodie",
    category: "hoodie",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 8, M: 12, L: 10, XL: 6, XXL: 3 },
    colors: ["black", "grey melange", "navy"],
    material: "cotton-poly fleece",
    gsm: 340,
    priceInr: 1799,
    theme: "solid",
    returnable: true,
    tags: ["winter", "warm", "heavyweight"],
  },
  {
    id: "TSS-HOD-002",
    name: "Cloud Oversized Hoodie",
    category: "hoodie",
    fit: "oversized",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 6, M: 9, L: 7, XL: 4 },
    colors: ["dusty pink", "cream"],
    material: "cotton-poly fleece",
    gsm: 320,
    priceInr: 1999,
    theme: "solid",
    returnable: true,
    tags: ["winter", "drop-shoulder", "soft-handfeel"],
  },
  {
    id: "TSS-HOD-003",
    name: "Featherlite Hoodie",
    category: "hoodie",
    fit: "regular",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 7, M: 10, L: 8, XL: 0 },
    colors: ["olive", "sand"],
    material: "cotton french terry",
    gsm: 260,
    priceInr: 1599,
    theme: "solid",
    returnable: true,
    tags: ["mid-weight", "transitional"],
  },
  {
    id: "TSS-SWT-001",
    name: "Varsity Sweatshirt",
    category: "sweatshirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 5, M: 8, L: 6, XL: 3 },
    colors: ["maroon", "heather grey"],
    material: "cotton-poly fleece",
    gsm: 300,
    priceInr: 1499,
    theme: "varsity print",
    returnable: true,
    tags: ["winter", "graphic"],
  },
  {
    id: "TSS-SWT-002",
    name: "Sunwashed Crewneck",
    category: "sweatshirt",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 6, M: 9, L: 7, XL: 4, XXL: 1 },
    colors: ["washed coral", "washed blue"],
    material: "cotton french terry",
    gsm: 280,
    priceInr: 1399,
    theme: "solid",
    returnable: true,
    tags: ["garment-wash", "mid-weight"],
  },

  // ---- Bottoms --------------------------------------------------------------
  {
    id: "TSS-JOG-001",
    name: "Everyday Joggers",
    category: "joggers",
    fit: "regular",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: { S: 10, M: 14, L: 12, XL: 7, XXL: 3 },
    colors: ["black", "charcoal", "navy"],
    material: "cotton-poly fleece",
    priceInr: 1299,
    theme: "solid",
    returnable: true,
    tags: ["athleisure", "warm"],
  },
  {
    id: "TSS-JOG-002",
    name: "Feather Knit Joggers",
    category: "joggers",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 8, M: 11, L: 9, XL: 4 },
    colors: ["grey melange", "sage"],
    material: "cotton-modal blend",
    priceInr: 1399,
    theme: "solid",
    returnable: true,
    tags: ["lightweight", "lounge", "breathable"],
  },
  {
    id: "TSS-JOG-003",
    name: "Cargo Joggers",
    category: "joggers",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 5, M: 7, L: 6, XL: 0 },
    colors: ["olive", "tan"],
    material: "cotton twill",
    priceInr: 1699,
    theme: "solid",
    returnable: true,
    tags: ["utility", "streetwear"],
  },
  {
    id: "TSS-SHR-001",
    name: "Chino Shorts",
    category: "shorts",
    fit: "regular",
    sizes: ["30", "32", "34", "36"],
    stock: { "30": 6, "32": 9, "34": 7, "36": 3 },
    colors: ["khaki", "navy"],
    material: "cotton twill",
    priceInr: 1199,
    theme: "solid",
    returnable: true,
    tags: ["summer", "smart-casual"],
  },
  {
    id: "TSS-SHR-002",
    name: "Lounge Shorts",
    category: "shorts",
    fit: "relaxed",
    sizes: ["S", "M", "L", "XL"],
    stock: { S: 9, M: 12, L: 10, XL: 5 },
    colors: ["grey melange", "black"],
    material: "cotton french terry",
    priceInr: 899,
    theme: "solid",
    returnable: true,
    tags: ["lounge", "soft-handfeel"],
  },

  // ---- Women's styles --------------------------------------------------------
  {
    id: "TSS-WTP-001",
    name: "Ribbed Crop Top",
    category: "top",
    fit: "slim",
    sizes: ["XS", "S", "M", "L"],
    stock: { XS: 6, S: 9, M: 7, L: 3 },
    colors: ["white", "black", "lilac"],
    material: "ribbed cotton-elastane",
    gsm: 220,
    priceInr: 799,
    theme: "solid",
    returnable: true,
    tags: ["stretch", "fitted", "summer"],
  },
  {
    id: "TSS-WTP-002",
    name: "Breeze Relaxed Top",
    category: "top",
    fit: "relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: { XS: 5, S: 8, M: 9, L: 6, XL: 2 },
    colors: ["sage", "cream", "blush"],
    material: "cotton-modal blend",
    gsm: 160,
    priceInr: 899,
    theme: "solid",
    returnable: true,
    tags: ["lightweight", "breathable", "drapey"],
  },
  {
    id: "TSS-WDR-001",
    name: "T-Shirt Dress",
    category: "dress",
    fit: "relaxed",
    sizes: ["XS", "S", "M", "L"],
    stock: { XS: 4, S: 7, M: 6, L: 2 },
    colors: ["black", "olive"],
    material: "100% cotton",
    gsm: 200,
    priceInr: 1299,
    theme: "solid",
    returnable: true,
    tags: ["one-piece", "mid-weight"],
  },
  {
    id: "TSS-WDR-002",
    name: "Summer Midi Dress",
    category: "dress",
    fit: "regular",
    sizes: ["XS", "S", "M", "L"],
    stock: { XS: 3, S: 6, M: 5, L: 0 },
    colors: ["floral print", "terracotta"],
    material: "viscose rayon",
    priceInr: 1699,
    theme: "floral print",
    returnable: true,
    tags: ["drapey", "lightweight", "resort"],
  },
  {
    id: "TSS-WOV-001",
    name: "Women's Oversized Graphic Tee",
    category: "oversized-tshirt",
    fit: "oversized",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: { XS: 5, S: 9, M: 8, L: 4, XL: 1 },
    colors: ["washed black", "lavender"],
    material: "100% cotton",
    gsm: 220,
    priceInr: 1099,
    theme: "retro pop",
    returnable: true,
    tags: ["graphic", "drop-shoulder", "mid-weight"],
  },

  // ---- Accessories (final sale under the demo policy) ------------------------
  {
    id: "TSS-ACC-001",
    name: "Logo Cap",
    category: "accessory",
    fit: "regular",
    sizes: ["OS"],
    stock: { OS: 20 },
    colors: ["black", "navy", "khaki"],
    material: "cotton twill",
    priceInr: 599,
    theme: "solid",
    returnable: false,
    tags: ["headwear", "final-sale"],
  },
  {
    id: "TSS-ACC-002",
    name: "Canvas Tote",
    category: "accessory",
    fit: "regular",
    sizes: ["OS"],
    stock: { OS: 15 },
    colors: ["natural", "black"],
    material: "canvas cotton",
    priceInr: 699,
    theme: "solid",
    returnable: false,
    tags: ["carry", "final-sale"],
  },
  {
    id: "TSS-ACC-003",
    name: "Beanie",
    category: "accessory",
    fit: "regular",
    sizes: ["OS"],
    stock: { OS: 12 },
    colors: ["charcoal", "maroon"],
    material: "acrylic knit",
    priceInr: 499,
    theme: "solid",
    returnable: false,
    tags: ["winter", "final-sale"],
  },
];

const byId = new Map(CATALOG.map((p) => [p.id, p]));

export function getProduct(id: string): Product | undefined {
  return byId.get(id);
}

export function normalizeId(id: string): string {
  return id.trim().toUpperCase().replace(/\s+/g, "");
}
